spring:
  application:
    name: Omegron

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/omegron_application?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  sql:
    init:
      mode: never

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

weather:
  api:
    key: ${WEATHER_API_KEY:NGSRXC2QYU6X2Q6BJ7R2WBMA8}
    url: "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/Drenov/{start_date}/{end_date}?unitGroup=metric&elements=datetime,name,address,latitude,longitude,tempmax,tempmin,temp,sunrise,sunset,conditions,description,icon,source&include=fcst,obs,remote,days&key={key_id}&contentType=json"
    address: "Drenov"

inventory:
  api:
    baseUrl: "http://localhost:8081"
#%2C encoded is "," !!!
