spring:
  application:
    name: Omegron
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/omegron_application?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080

weather:
  api:
    key: ${WEATHER_API_KEY:}
    url: "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/Drenov/2024-07-08/2024-07-22?unitGroup=metric&elements=datetime%2Cname%2Caddress%2Clatitude%2Clongitude%2Ctempmax%2Ctempmin%2Ctemp%2Csunrise%2Csunset%2Cconditions%2Cdescription%2Cicon%2Csource&include=fcst%2Cobs%2Cremote%2Cdays&key={key_id}&contentType=json"
    address: "Drenov"
